spring:
  application:
    name: demo-temporal
  datasource:
    url: jdbc:sqlite:D:/tmp/test-temporal/fileprocessing.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

temporal:
  server-address: localhost:7233
  namespace: default
  task-queue: demo-task-queue
  source-path: D:/tmp/test-temporal/source
  source-path2: D:/tmp/test-temporal/source2
  source-path3: D:/tmp/test-temporal/source3
  source-path4: D:/tmp/test-temporal/source4
  target-path: D:/tmp/test-temporal/target

  server:
    rpc-timeout: 10s
    connection-backoff-reset-frequency: 10s
    grpc-reconnect-frequency: 10s
    enable-https: false

  worker:
    max-concurrent-workflow-task-execution-size: 200
    max-concurrent-activity-execution-size: 200
    max-concurrent-local-activity-execution-size: 200
    min-pollers: 2
    init-pollers: 5
    max-pollers: 200
    deadlock-detection-timeout: 10000
